### ISSUE TITLE
How to inference on one GPU?

### ISSUE THREAD

**Issue by liguoyu666** [NVIDIA/semantic-segmentation#102]
I download the weights,  change `--nproc_per_node=8` to `--nproc_per_node=1`, and change `__C.DATASET.CITYSCAPES_DIR = os.path.join(__C.ASSETS_PATH, 'data/Cityscapes')` to "imgs/test_imgs" .  

![image](https://user-images.githubusercontent.com/47743761/100857522-ba14e580-34c7-11eb-9216-c1bee9efee8b.png)

**Comment by ajtao** [comment]
That should work. Make sure you have killed previous processes.

**Comment by liguoyu666** [comment]
> That should work. Make sure you have killed previous processes.

I want to inference my own images, and in eval_cityscapes.yml I set 'eval' to 'folder', but when I run, it reported the eval_folder (a path to directory with *only* images files) is None,  What shold I set it up?

**Comment by liguoyu666** [comment]
I run with `python -m torch.distributed.launch --nproc_per_node=1 train.py --arch ocrnet.HRNet_Mscale --multi_scale_inference --eval folder --eval_folder imgs/test_imgs --snapshot ASSETS_PATH/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth `, The code is working properly, But I have to download 'hrnetv2_w48_imagenet_pretrained.pth', is the weight necessary? 
And my GPU is GTX1060 6G, it reports "CUDA out of memory." need larger menory on inference?

**Comment by liguoyu666** [comment]
I use GTX2080Ti 11G, it also reports "CUDA out of memory" , Then I use 4 GPUs,  but it seems run with only gpu:0, I just infer not train the model. 
`export CUDA_VISIBLE_DEVICES='0,1,2,3' `
`python -m torch.distributed.launch --nproc_per_node=4 train.py --arch ocrnet.HRNet_Mscale --multi_scale_inference --eval folder --eval_folder imgs/test_imgs --snapshot ASSETS_PATH/seg_weights/cityscapes_ocrnet.HRNet_Mscale_outstanding-turtle.pth`

**Comment by ajtao** [comment]
Yes the code requires you to download that pretrained model. 
If you're running out of memory, i can't really help.

**Comment by liguoyu666** [comment]
> Yes the code requires you to download that pretrained model.
> If you're running out of memory, i can't really help.

Thank you

**Comment by xinghaoxinghao** [comment]
Did you achieve in single GPU？
