### ISSUE TITLE
Should we pull NGC Pytorch container or can we use offical pytorch container in building docker file ?

### ISSUE THREAD

**Issue by jakvivin** [NVIDIA/semantic-segmentation#108]
Hi

Can we use official PyTorch docker image ? or we should compulsory go for NGC as mentioned in docker file? ,What is the reason we are using NGC container? When i try to build with Official PyTorch image with similar version that is mentioned in NGC Documentation (Layered steps) ,I am facing issue and getting error,Can u help me with necessary steps

Thank You

**Comment by karansapra** [comment]
I believe you can pull from pytorch. the NGC container changes should also be in pytorch currently. Let us know if you see issues when you use the pytorch docker image.

**Comment by jakvivin** [comment]
Yeah I am getting error wen setuping apex ,I am getting issue in installing apex like 

`Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    raise RuntimeError("--cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.")
RuntimeError: --cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc,`

 i couldnt built the image , i have checked with nvcc --version  ans nvidia-smi Can u help me with clear steps

**Comment by jakvivin** [comment]
Thank You ,I resolved it
