### ISSUE TITLE
What is the additional cityscapes `train_extra` data needed for SOTA training?

### ISSUE THREAD

**Issue by sreenjoyDE** [NVIDIA/semantic-segmentation#118]
Hello,

Thank you for sharing your work. Very intuitive README and code structure is very well documented.

I ran some eval tests as mentioned in the README and they went well, I get the exact same IoU of 86.92 for `eval_cityscapes.yml`

Next, I tried `train_cityscapes.yml`. I needed to bump down the crop size to `512, 1024` because I was running out of memory, and that worked as well. **Please comment if this reduction** in `crop_size` could have an impact on IoU accuracy.

My main question, however, is when I try to train `train_cityscapes_sota.yml` it breaks while looking for this data folder. `leftImg8bit_trainextra/leftImg8bit/train_extra`

Could you please share what is this additional / extra data needed from cityscapes to train the sota run? Or was this just a different split that you tried from the original dataset?

![Screenshot 2021-02-17 at 18 55 50](https://user-images.githubusercontent.com/57751334/108246469-c23d0280-7151-11eb-9517-e3b191598a40.png)

**Comment by sreenjoyDE** [comment]
found it in `https://github.com/NVIDIA/semantic-segmentation/blob/main/PREPARE_DATASETS.md`, thanks

**Comment by foranonymous123** [comment]
Hi @sreenjoyDE 

Sorry for reopening this issue, I was wondering how you achieve 86.92 by running eval_cityscapes.yml. I got 0.91 or 91 something, much higher. I don't know why.

Appreciate your reply!
