### ISSUE TITLE
Question about cropping operation in sdcnet

### ISSUE THREAD

**Issue by visionxyz** [NVIDIA/semantic-segmentation#121]
https://github.com/NVIDIA/semantic-segmentation/blob/b4fc685bb35d9b7547b805b1395c515876ec48db/sdcnet/datasets/frame_loader.py#L87

Here, height, width = input_shape, but input_shape is the shape before cropping. Why the padding operation on cropped images use the original shape? I think it should use the cropped size? Thanks!

**Comment by fitsumreda** [comment]
The padding logics are relevant more for eval/inference, and the proceeding cropping logics for training. The padding allows inference for arbitrarily shaped input sequences. In training, crop_size is assumed to be selected to evenly fit into the models.

**Comment by visionxyz** [comment]
I see. Thank you so much!
