### ISSUE TITLE
Unable to run train.py on Mapillary ('experiment file is missing hparams')

### ISSUE THREAD

**Issue by aoussou** [NVIDIA/semantic-segmentation#126]
Hello,

Is this the correct command to train on the Mapillary dataset?

`python -m runx.runx scripts/train_mapillary.yml -i`

I get the following error:

`assert 'HPARAMS' in experiment, 'experiment file is missing hparams'`

**Comment by ajtao** [comment]
fixed, please pull the latest scripts/train_mapillary.yml
