### ISSUE TITLE
where your pictures?

### ISSUE THREAD

**Issue by zhujiesuper** [NVIDIA/semantic-segmentation#128]
your job is awesome,but i can not find the two photos(cityscapes) in your paper.can you tell me where them?  in val ? or train? or test?

**Comment by ajtao** [comment]
Have a look at the video portion of the Cityscapes dataset, i believe that's where the photos are from.

**Comment by zhujiesuper** [comment]
i have search the cityscapes，but their too much photos，i can not find the two photos in
paper





------------------ Original ------------------

**Comment by ajtao** [comment]
stuttgart_00_000000_000090_leftImg8bit.png, stuttgart_00_000000_000272_leftImg8bit.png
As i said, they're part of the demoVideo dataset.
