### ISSUE TITLE
or can you send me the two photos in video part?

### ISSUE THREAD

**Issue by zhujiesuper** [NVIDIA/semantic-segmentation#130]
stuttgart_00_000000_000090_leftImg8bit.png, stuttgart_00_000000_000272_leftImg8bit.png
my email is 653725215@qq.com

**Comment by ajtao** [comment]
I endeavor to help people with their issues in this project, but it is not my job to teach people to become data scientists.

Please go to the Cityscapes website. Find the Video dataset. Extract it into frames and you will find those frames that are in the paper.
