### ISSUE TITLE
Fail to run inference and dump images on a folder of images

### ISSUE THREAD

**Issue by xinghaoxinghao** [NVIDIA/semantic-segmentation#138]
when I try to run inference and dump images on a folder of images,the output is shown .
![image](https://user-images.githubusercontent.com/38419495/115995868-8a4db200-a60f-11eb-8171-07581b628181.png)

**Comment by karansapra** [comment]
Hmm, this is weird its not able to detect train.py, can you check train.py exists in the location above (rough bird ) , please.

**Comment by ajtao** [comment]
Hello, the way the scripts here work is that they first try to create a new "run" directory under LOGROOT, which is defined in your .runx file. All the code is copied there, and then the training job is run from within that "run" directory. The idea is that this preserves the state of the code and also saves all the log output into a single "run" directory tree, so you can refer back to this saved state in the future, if needed.

In your case, the "run" directory is `logs/dump_folder/rough-bird_...`. If the directory `logs` doesn't exist, then it would have this complaint that you're seeing.

**Comment by xinghaoxinghao** [comment]
> Hello, the way the scripts here work is that they first try to create a new "run" directory under LOGROOT, which is defined in your .runx file. All the code is copied there, and then the training job is run from within that "run" directory. The idea is that this preserves the state of the code and also saves all the log output into a single "run" directory tree, so you can refer back to this saved state in the future, if needed.
> 
> In your case, the "run" directory is `logs/dump_folder/rough-bird_...`. If the directory `logs` doesn't exist, then it would have this complaint that you're seeing.

**Comment by xinghaoxinghao** [comment]
Thank you.However，the directory 'logs' have existed, and the code can copy sucessfully when i run inference and dump images on a folder of images.
![image](https://user-images.githubusercontent.com/38419495/116020596-337cc280-a679-11eb-9f4d-c7fe858386ac.png)

**Comment by xinghaoxinghao** [comment]
> Hello, the way the scripts here work is that they first try to create a new "run" directory under LOGROOT, which is defined in your .runx file. All the code is copied there, and then the training job is run from within that "run" directory. The idea is that this preserves the state of the code and also saves all the log output into a single "run" directory tree, so you can refer back to this saved state in the future, if needed.
> 
> In your case, the "run" directory is `logs/dump_folder/rough-bird_...`. If the directory `logs` doesn't exist, then it would have this complaint that you're seeing.

**Comment by desti-nation** [comment]
> Thank you.However，the directory 'logs' have existed, and the code can copy sucessfully when i run inference and dump images on a folder of images. ![image](https://user-images.githubusercontent.com/38419495/116020596-337cc280-a679-11eb-9f4d-c7fe858386ac.png)

have you addressed this problem? I meet the save question.
