### ISSUE TITLE
Pre-training Dataset

### ISSUE THREAD

**Issue by visionxyz** [NVIDIA/semantic-segmentation#150]
Hi, thanks for your works! I am currently doing related works. As you said in the sdcnet paper:
> We collected 428K 1080p frames from GTA-V and Battlefield-1 game plays. Each example consists of five (t=5) consecutive 256×256 frames randomly cropped from the full-HD sequence. We use a batch size of 128 over 8 V100 GPUs.

**I am wondering whether it is possible to get the GTA-V and Battlefield-1 data? Or is there any guideline for collecting data from Battlefield-1**
Thanks for your help! I know that it may be hard to provide the data of GTA-V and Battlefield-1.

**Comment by fitsumreda** [comment]
Thanks for your interest in the work. Unfortunately, that dataset isn't publicly available due to IP.

**Comment by visionxyz** [comment]
Thanks again！
