### ISSUE TITLE
How to train custom dataset?

### ISSUE THREAD

**Issue by yes89929** [NVIDIA/semantic-segmentation#152]
Hi. Thanks you for shairing good code.
But, I`m not familiar with deeplearning and pytorch.

I want to train your model using my custom datasets. And, My custom dataset has 4 classes with void class(0).

May I have some hint tor training my custom datasets?

**Comment by ajtao** [comment]
I'm sorry, it's like asking for a data science class. Why don't you try to learn from [pytorch examples](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html).
