### ISSUE TITLE
GPU utilization during evaluation

### ISSUE THREAD

**Issue by bryanyzhu** [NVIDIA/semantic-segmentation#16]
Hi @karansapra  I noticed a weird GPU memory consumption during evaluation. 

If I use 4 GPUs, the memory starts to increase on GPU 0, and then GPU 1, and then GPU2. It never use the 4th GPU. I attached my screenshot as below. 

![4_cards](https://user-images.githubusercontent.com/16021460/62890299-19aa1900-bcf8-11e9-9966-080f4153d697.png)

Similarly, if I use 8 GPUs, the code only uses 6 of them, the rest two are idle. The screenshot is as below. 

![image](https://user-images.githubusercontent.com/16021460/62890635-b7054d00-bcf8-11e9-84c9-ab79ec433475.png)

It seems that the code only choose to use more GPUs if they have to use. In addition, most of the time, the GPU utilization is 0, which means the speed is limited by IO or other data processing. 

Could you look into this please? @karansapra I think if we can fully utilize all the GPUs, the evaluation will be faster. But maybe this is just the problem of my machine, let me know if you can reproduce this on your end. Thank you very much.

**Comment by karansapra** [comment]
Will have a look this week.

**Comment by karansapra** [comment]
I have debugged, I  am going to rewrite this code over the weekend. :)

**Comment by bryanyzhu** [comment]
@karansapra Wonderful, appreciate it.
