### ISSUE TITLE
it seems that there is no Spatially Displaced Convolution in sdc_net2d.py?

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [NVIDIA/semantic-segmentation#17]
it seems that there is no Spatially Displaced Convolution in dir [sdcnet](https://github.com/NVIDIA/semantic-segmentation/tree/master/sdcnet) as described in the paper `SDCNet: Video Prediction Using Spatially Displaced Convolution. ECCV 2018`? in the file [sdc_net2d.py](https://github.com/NVIDIA/semantic-segmentation/blob/master/sdcnet/models/sdc_net2d.py),  a CNN model is used to refine the input  optical flow(flownet2 output), while there is no **Spatially Displaced Convolution**?

**Comment by bryanyzhu** [comment]
Yes, this is only a partial release of sdcnet @fitsumreda, there is no spatially displaced convolution. Since we only need motion vectors from sdcnet to propagate labels, we don't use the learned kernels in this project.

**Comment by Jiangfeng-Xiong** [comment]
ok, thank you

**Comment by fitsumreda** [comment]
@Jiangfeng-Xiong, FYI. We have added the CUDA kernel for the Spatially Displaced Convolution (SDC) layer presented in  `SDCNet: Video Prediction Using Spatially Displaced Convolution. ECCV 2018`

**Comment by bryanyzhu** [comment]
@fitsumreda Awesome, thank you.
