### ISSUE TITLE
Train with NuImages Dataset

### ISSUE THREAD

**Issue by LAZOO61** [NVIDIA/semantic-segmentation#172]
Hello,
I would like to train with the NuImages data set.  How could I integrate this? Do I have to write a data loader?

**Comment by karansapra** [comment]
Hello, yes, unfortunately, we don't have a NuImage data loader so you will have to write one.

**Comment by LAZOO61** [comment]
Thank you. How can I write a data loader? Can I take and change an existing data loader or do you have to write one completely yourself?

**Comment by LAZOO61** [comment]
?
