### ISSUE TITLE
can you provide the testing for single image?

### ISSUE THREAD

**Issue by shiguangjiing** [NVIDIA/semantic-segmentation#20]

**Comment by bryanyzhu** [comment]
Hi, you mean inference on a single image, right? 

I just made a PR to this repo. You can have a look at [here](https://github.com/NVIDIA/semantic-segmentation/blob/56c8bc11121b6e488aa0b57253b1f661cee665a2/demo.py). You can simply use this `demo.py` to test any driving scene images. The command line should be like

```
CUDA_VISIBLE_DEVICES=0 python demo.py --demo-image YOUR_IMG --snapshot ./pretrained_models/cityscapes_best_wideresnet38.pth --save-dir YOUR_SAVE_DIR
```
If I didn't understand your issue, please let me know. Thank you.

**Comment by shiguangjiing** [comment]
Thanks!


------------------ 原始邮件 ------------------
发件人: "Yi Zhu"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 下午2:10
收件人: "NVIDIA/semantic-segmentation"<semantic-segmentation@noreply.github.com>;
抄送: "计研—仵晨阳"<794273584@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NVIDIA/semantic-segmentation] can you provide the testing forsingle image? (#20)




Hi, you mean inference on a single image, right?
 
I just made a PR to this repo. You can have a look at here. You can simply use this demo.py to test any driving scene images. The command line should be like
 CUDA_VISIBLE_DEVICES=0 python demo.py --demo-image YOUR_IMG --snapshot ./pretrained_models/cityscapes_best_wideresnet38.pth --save-dir YOUR_SAVE_DIR  
If I didn't understand your issue, please let me know. Thank you.

**Comment by karansapra** [comment]
Closing the bug :) Thanks @bryanyzhu
