### ISSUE TITLE
How can I get the video data of CamVid?

### ISSUE THREAD

**Issue by irfanICMLL** [NVIDIA/semantic-segmentation#22]
Thank you for your great work!
Could you please help with the data pre-processing?
How can I get the video data of Camvid?
I only find some MXF video on the official database page, but the link to the code of pre-processing is broken.

Thanks,
yifan

**Comment by irfanICMLL** [comment]
Thank you for your quick reply.
The SegNet only has the scaled data with 480*360, and only the labeled ones.
 What is the source data you use to implement the aug?
I thought there are some unlabeled video data like the sequence in Cityscapes.

**Comment by irfanICMLL** [comment]
Would you mind to share the unlabeled video data, so that we can reproduce your experiments?

Thanks!

**Comment by bryanyzhu** [comment]
I'm sorry but I don't have that data available. I left those when the internship ends. As I mentioned, decoding the videos [here](http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamVid/) will give you the unlabeled video frames, you should have the same data as mine. Sorry about the inconvenience.

**Comment by irfanICMLL** [comment]
What a pity.
By the way, have you used the pre-trained weight on cityscapes to train your CamVid model?

**Comment by bryanyzhu** [comment]
Yes, I used it. As shown in my experiments and previous VideoGCRF work, using pre-trained weight on Cityscapes to train CamVid is very helpful.

**Comment by irfanICMLL** [comment]
Thanks for your help.

**Comment by giulionf** [comment]
Seems like the project moved here: http://web4.cs.ucl.ac.uk/staff/g.brostow/MotionSegRecData/

Here's a little script that downloads and preprocessed the dataset for you: https://github.com/giulionf/download-camvid
*Note*: It does simply download the videos and processes the frames, it does not split into train/test/val yet.
