### ISSUE TITLE
Code for SDC Net

### ISSUE THREAD

**Issue by NagabhushanSN95** [NVIDIA/semantic-segmentation#36]
Hi,
Can you share the code and pretrained models (if available) for SDC-Net? I saw [SDC Net github.io page](https://nv-adlr.github.io/publication/2018-SDCNet), but it doesn't have a link for the code.

**Comment by bryanyzhu** [comment]
Hi, the code for SDC layer is at:

https://github.com/NVIDIA/semantic-segmentation/tree/master/sdcnet/spatialdisplconv_package

And our pretrained SDCNet model on Cityscapes is at:

https://drive.google.com/file/d/1OxnJo2tFEQs3vuY01ibPFjn3cRCo2yWt/view?usp=sharing

However, the full pipeline and pretrained models in the original SDCNet paper are not available in this repository.

**Comment by NagabhushanSN95** [comment]
Thank you. Is there a separate repository for SDC net? If so, can you provide the link for that?

**Comment by bryanyzhu** [comment]
I'm sorry, but I don't think there is a separate repository for SDCNet at this moment.
