### ISSUE TITLE
Would you please provide the training script for the  SDCNet?

### ISSUE THREAD

**Issue by tfzhang006** [NVIDIA/semantic-segmentation#38]

**Comment by bryanyzhu** [comment]
You mean the training script for the video reconstruction model used in this paper? Or for the model in original SDCNet paper?

**Comment by tfzhang006** [comment]
I mean the training script for video reconstruction model used in this paper.

**Comment by bryanyzhu** [comment]
I will try to get it to you in this week.

**Comment by tfzhang006** [comment]
Thanks for your help.

**Comment by bryanyzhu** [comment]
Hi, as far as I can recall, the command line is like below

```
python main.py --batch_size 8 \ 
               --epochs 400 \
               --lr 1e-4 \
               --sequence_length 3 \
               --dataset FrameLoader  \
               --train_file ???
```

But I don't remember the details and the code has been changed significantly when I used it. I'm not sure what `train_file` should be. 

@fitsumreda Can you comment more on this issue? Thank you very much.
