### ISSUE TITLE
insufficient shared memory (shm)

### ISSUE THREAD

**Issue by chipkajb** [NVIDIA/semantic-segmentation#42]
Hello,

Thank you for providing your code!

I am having a lot of trouble getting this to train properly. I have tried training on many different machines and it always crashes with the same error.

`ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)`.

My latest two attempts have been on a machine with four Tesla P100 SXM2's (16 GB each), and then on a machine with one Titan RTX (24 GB). The training crashes on the first iteration on the machine with four Tesla P100 SXM2's. With the Titan RTX, however, I make it through the first epoch of training, but then it crashes on the first iteration in validation. By watching `nvidia-smi` while trying to train with the Titan RTX, I can see that there is a spike in memory to >19GB during training, and then there must be another spike to >24GB during evaluation which causes the crash with the Titan RTX.

I am using the latest version of this code. Is there anyway to further mitigate these memory spikes? It seems like a 24 GB GPU ought to be enough.

Thank you!

**Comment by chipkajb** [comment]
Also, I've tried dropping `crop_size` to as low as 128, but I still run into the same problem.

**Comment by chipkajb** [comment]
Another clarification, this error occurs when trying to pre-train with Mapillary data. It appears to work for fine-tune training with Cityscapes.

**Comment by bryanyzhu** [comment]
The error message shows you have insufficient shared memory (shm). It is not GPU memory. 

If you type `df -h`, you will find something like below, 

```
Filesystem      Size  Used Avail Use% Mounted on
udev            241G     0  241G   0% /dev
tmpfs            49G   73M   48G   1% /run
/dev/xvda1      1.9T  875G  1.1T  46% /
tmpfs           241G     0  241G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           241G     0  241G   0% /sys/fs/cgroup
/dev/loop1       18M   18M     0 100% /snap/amazon-ssm-agent/1480
/dev/loop3       18M   18M     0 100% /snap/amazon-ssm-agent/1455
```

The `/dev/shm` shows how much shared memory you have. In this case, I think your shared memory is not big enough to train the model. You need to either decrease batch size or crop size, or find a way to increase your shared memory.

**Comment by bryanyzhu** [comment]
You can search "insufficient shared memory during pytorch training", you will find plenty of posts on this error. 

Here is a relevant one, https://discuss.pytorch.org/t/training-crashes-due-to-insufficient-shared-memory-shm-nn-dataparallel/26396/9

Use less `num_workers` in [dataloader](https://github.com/NVIDIA/semantic-segmentation/blob/master/datasets/__init__.py#L263-L266) will solve this problem. 
https://github.com/NVIDIA/semantic-segmentation/blob/master/datasets/__init__.py#L67

**Comment by chipkajb** [comment]
Ah I see. Ok thank you!
