### ISSUE TITLE
Reproduce results on CamVid

### ISSUE THREAD

**Issue by Awannen** [NVIDIA/semantic-segmentation#43]
Hi,

I just tried to reproduce the results on CamVid using the provided checkpoint in pretrained_models/camvid_best.pth as well as the validate() function in train.py. I downloaded the CamVid dataset from the SegNet tutorial indicated in the readme. Here, the images have size 360x480. However, with this data I obtain results with a miou around 75% on the indicated test split of 233 images. 
Due to the crop size of 640, I now assume that you used the large scale version of the dataset. Is this correct? If this is the case: which approach did you follow to merge the 32 original classes into 11?

Many thanks in advance.

**Comment by bryanyzhu** [comment]
Yes, we use the large scale version of the dataset. You can simply use bilinear operation to scale up your data, from 360x480 to 720x960. 

We also try to merge the classes before, found similar results, but I don't remember which approach we follow. I would suggest just upscaling your data.

**Comment by Awannen** [comment]
When upscaling the small scale labels with nearest neighbor interpolation and using the original full scale images, I get an miou of 81.6%. This matches the reported result quite well.
Thanks for the clarification.
