### ISSUE TITLE
tarfile.EmptyHeaderError: empty header

### ISSUE THREAD

**Issue by sieuwe1** [NVIDIA/semantic-segmentation#44]
Hi

I am having a problem when I try to run the demo.py. When I run the following command:

```python3 demo.py --demo-image test.png --snapshot pretrained_models/cityscapes_best.pth ```

I get the error:
```
Using regular batch norm
Net built.
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1029, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2312, in next
    raise ReadError("empty file")
tarfile.ReadError: empty file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    net, _ = restore_snapshot(net, optimizer=None, snapshot=args.snapshot, restore_optimizer_bool=False)
  File "/home/sieuwe/Downloads/semantic-segmentation-master/optimizer.py", line 69, in restore_snapshot
    checkpoint = torch.load(snapshot, map_location=torch.device('cpu'))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 597, in _load
    if _is_zipfile(f):
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 75, in _is_zipfile
    if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found

```
I believe the error accours when it is loading the pretrained_models/wider_resnet38.pth.tar. But I dont know what I have done wrong.

The steps I followed where:
- clone repo
- Install all dependencies
- download cityscapes_best.pth and wider_resnet38.pth.tar
- make a folder called pretrained_models in repo root and add the two mentioned files.
- type above mentioned command to run demo. 

My system
Ubuntu 18.4 LTS
python 3.6
Cuda 10.2
Driver 440.33.01 
card GTX1080

PS: I am also wondering if there is a python video implementation for this network which can take a normal video as input? Because the Demo.py is only for images right?
Or can I make a loop which loops over a video and per frame makes a prediction using the net(img) function. 
If that is possible what will the FPS be for such an implementation on a GTX1080?

Thanks

Sieuwe

**Comment by karansapra** [comment]
Hi @sieuwe1 could be the download is corrupted could you provide md5sum for cityscapes_best.pth. I think the file probably didn't download correctly, could you try that as well.

As for FPS, I am not really sure. We never really tried it, I would say if you want to get the best number, we should run the network in half ( fp16 ) and on a GPU which supports tensor core for maximum fps.

**Comment by sieuwe1** [comment]
Hi @karansapra 

I dont know why but after re downloading the cityscapes_best.pth file it worked!

I still have one question. The demo.py is for images. Which python file is for video? Or should I use the demo.py code and loop that code over every frame in a video?

Thanks 

Sieuwe

**Comment by bryanyzhu** [comment]
Glad it worked. 

The `demo.py` is for single image. We don't have a `video_demo.py` yet, maybe I can add it later. At this moment, I think your suggested way sounds good, just modify `demo.py` a bit to loop every frame in the video.

**Comment by bryanyzhu** [comment]
@sieuwe1 I add a `demo_folder.py` in the pull request. You can use it to directly inference on a folder of images. You will also obtain colored predictions and overlapping predictions.

```
python demo_folder.py --demo-folder YOUR_FOLDER --snapshot ./pretrained_models/cityscapes_best.pth --save-dir YOUR_SAVE_DIR
```

**Comment by sieuwe1** [comment]
Hi @bryanyzhu 

Thanks for the Demo. I have actually made an implementation of my own which accepts normal .mp4 videos. Here is the code below:
```

import os
import sys
import argparse
from PIL import Image
import numpy as np
import cv2

import torch
from torch.backends import cudnn
import torchvision.transforms as transforms

import network
from optimizer import restore_snapshot
from datasets import cityscapes
from config import assert_and_infer_cfg

parser = argparse.ArgumentParser(description='demo')
parser.add_argument('--demo-image', type=str, default='', help='path to demo image', required=True)
parser.add_argument('--snapshot', type=str, default='./pretrained_models/cityscapes_best.pth', help='pre-trained checkpoint')
parser.add_argument('--arch', type=str, default='network.deepv3.DeepWV3Plus', help='network architecture used for inference')
parser.add_argument('--save-dir', type=str, default='./save', help='path to save your results')
args = parser.parse_args()
assert_and_infer_cfg(args, train_mode=False)
cudnn.benchmark = False
torch.cuda.empty_cache()

# get net
args.dataset_cls = cityscapes
net = network.get_net(args, criterion=None)
net = torch.nn.DataParallel(net).cuda()
print('Net built.')
net, _ = restore_snapshot(net, optimizer=None, snapshot=args.snapshot, restore_optimizer_bool=False)
net.eval()
print('Net restored.')

# get data
mean_std = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
img_transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(*mean_std)])

cap = cv2.VideoCapture("KleinMoorst.mp4")

while True:

    ret, img = cap.read()
    if not ret:
        break

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    cv2.imshow("in", img)
    #img = Image.open(args.demo_image).convert('RGB')
    img_tensor = img_transform(img)

    # predict
    with torch.no_grad():
        img = img_tensor.unsqueeze(0).cuda()
        pred = net(img)
        print('Inference done.')

    pred = pred.cpu().numpy().squeeze()
    pred = np.argmax(pred, axis=0)
    np.savetxt('test.txt', pred, delimiter=',')
    
    colorized = args.dataset_cls.colorize_mask(pred)

    image = cv2.cvtColor(np.array(colorized), cv2.COLOR_RGB2BGR)
    print(image)
    cv2.imshow("out", image)
   
    ch = 0xFF & cv2.waitKey(1)
    if ch == 27:
        break

```

The code is not really clean yet and the imshow function to show to mask on the image is not working yet. 

But it is working and when I do imwrite on the mask it does write the correct mask. 
The only problem is that it is pretty slow. Only around 3/4 fps on my gtx1080 with 100% usage in nvidia-smi monitor.

How could in improve the performance? I only need the road, buildings and vehicle classes since I am planning to use this model on a self driving vehicle for a school project. 

Thanks for your help!

Sieuwe

**Comment by bryanyzhu** [comment]
There are several ways to make it faster,

1. Use a smaller network. We provide a SE-ResNeXt50 model in the readme, the download link is [here](https://drive.google.com/file/d/1aGdA1WAKKkU2y-87wSOE1prwrIzs_L-h/view?usp=sharing). It should be at least twice faster without losing much accuracy. Actually, if you only visualize the mask, you won't notice the difference. 

2. Do inference on a batch of images, not on a single image. For example, you can first read 8 video frames, turn it into a batch, 8x3x1024x2048, do the inference, and then separate the predictions and save them to disk. This will speed up a lot. 

3. You can also rescale your input image to a smaller size. 1024x2048 is too large, you can inference on 256x512 input images, get the predictions, and interpolate back to 1024x2048. This will save ton of time. 

4. You can definitely try some network pruning or compression technology, but that takes extra effort. I just put it here to for you to be aware.

**Comment by sieuwe1** [comment]
Thank you very much for the tips will try them out. 

I have two more questions. 

What sort of image is the colorized mask. Because I thought it was a PIL image so i converted it to opencv image using np.array(colorized) but it gives me a black screen?

I actually only want to know where the side of the road  is not the entire road. The network returns an numpy array with an x,y the same as width, height of the input image. Where every numpy x,y element is an integer which represents the class for that pixel on that x,y cordinate in the real image. so for example if pixel 100,100 is of class road the corresponding x = 100 y = 100 in the numpy array will be 0 because 0 is the class of roads. Is this correct?

Because I could then simply loop over the array and then keep track of previous pixel and the current pixel. If the previous pixel was not zero and the current one is 0 than that pixel is the side of the road. 

Greetings,

Sieuwe

**Comment by bryanyzhu** [comment]
1. Colorized mask is a special format, called palette in PIL library, you can check this [function](https://github.com/NVIDIA/semantic-segmentation/blob/1dc5e3bc7bd48d438199374afc199a4ad6ddcdad/datasets/cityscapes.py#L34) to see how we change it into the palette format. In order to change it to opencv image, please use `np.array(colorized.convert('RGB'))`. This will change its format from palette to RGB first, and then transform into opencv image. 

2. Yes, you are right. Semantic segmentation is a per-pixel estimation problem. You can just loop over all the pixels to find the edge of road. Although there maybe some artifacts due to wrong prediction, you can use algorithms like connected components to smooth it out.

**Comment by sieuwe1** [comment]
Thank you very much. 

1 `np.array(colorized.convert('RGB'))` works great!

2 Great ill try out connected components for smoothing once I am at that stage. 

Thanks for all your advice 

Really appreciate NVIDIA making this open source so that students like me can use these very advanced techniques for free.

Greetings 

Sieuwe

**Comment by sieuwe1** [comment]
Hi @bryanyzhu 

When i try to use the SE-ResNeXt50 I am getting really bad results. See the picture below as example. Top image is from your WideResNet38 model, second image is SE-ResNeXt50 downloaded from the link you gave me and last image is the input image. 

![Screenshot from 2019-12-16 20-49-05](https://user-images.githubusercontent.com/5994718/70938513-96525880-2046-11ea-8e1c-8879a4108ece.png)

![Screenshot from 2019-12-16 20-48-53](https://user-images.githubusercontent.com/5994718/70938522-9ce0d000-2046-11ea-9887-0656ad50eb69.png)

![Screenshot from 2019-12-16 20-50-34](https://user-images.githubusercontent.com/5994718/70938526-9eaa9380-2046-11ea-824f-a73f53c9f42e.png)

Thanks

Sieuwe

**Comment by bryanyzhu** [comment]
@sieuwe1 Does SE-ResNeXt50 perform bad on just this one image? Or bad on all the images? 

If it only works bad on some images, it is reasonable given its small model size. But if it works bad on most images, then something is wrong, either model loading or data preprocessing (i.e., normalization, crop, etc.).

**Comment by sieuwe1** [comment]
Hi @bryanyzhu 

The problem is for every image. The images above are screenshots of my demo.py program which loops over every frame of a video. And every frame it has a bad result. The screenshots are from one random frame in the video. 

I have not changed anything to the image pipeline. the only thing I have done was downloading the image and adding it to the petrained models folder. Then running demo.py with the SE-ResNeXt50. 

Thanks

Sieuwe

**Comment by bryanyzhu** [comment]
@sieuwe1 If every image has bad result, the error has to be in the model loading part. 

I just found the reason. When you switch pretrained model, you also need to specify the network architecture. Adding `--arch network.deepv3.DeepSRNX50V3PlusD_m1` in your command line will solve this problem. Try it and let me know. 

I will add some assertion check in the code to make sure this doesn't happen anymore.

**Comment by sieuwe1** [comment]
@bryanyzhu 

Yes that was the problem works perfectly now. Would not say that it is twice as fast but definitely faster!

Also made it that the model only analysis the video every 10th frame. This speeds up the program a lot so that it is now very usable for my self driving vehicle.

Thanks for your help again

Greetings

Sieuwe

**Comment by sieuwe1** [comment]
@bryanyzhu 

I have been making a lot of progress and your network is working really well. But I am now having the problem that the pc I am running it on requires to much power for the batteries of my autonomous vehicle. So I am looking at something more embedded like the Jetson Nano. Do you know what kind of FPS I can expect with a Jetson Nano?

Thanks

Sieuwe

**Comment by bryanyzhu** [comment]
Hi Sieuwe, I'm sorry I don't know, I didn't experiment on Jetson Nano before. But I'm interested in the performance if you manage to make it work on Nano. 

BTW, if the current network is not fast enough on embedded device, you may try real-time models such as FastSCNN. I have a trained FastSCNN model which works well, but unfortunately I can't share it at this moment. If you need speed, you can check a reference implementation at [here](https://github.com/lxtGH/Fast_Seg/blob/master/libs/models/FastSCNN.py).

**Comment by sieuwe1** [comment]
@bryanyzhu 

If you are interested to see what I made using your model and how it performs in my application you can watch this youtube video I made about it.

https://youtu.be/fH-g9boR2qA

It works already really well and thanks again for sharing the model.

I also tested your model on the Jetson with the realtime implementation I made. It does not perform well sadly. Around 1 fps and sometimes even lower. This is when I just make a while loop and every loop call the predict function. No optimization like batch processing. If you find it is useful I can do some more testing on the Jetson for you.

Thanks 

Sieuwe

**Comment by bryanyzhu** [comment]
Hi Sieuwe, I just watched your YouTube video, it is awesome and inspiring!! Your self-driving car looks fantastic. I also subscribed to your channel, other videos are interesting too. 

As for Jetson device, I think you need a much lighter model, otherwise the fps will be bad. I can update you with a real-time model in the future, and maybe you can test it on Jetson again. 

Great work!

**Comment by LuoXin0826** [comment]
Hi @sieuwe1, I saw your awesome work in your Youtube. I also wanna build this system on my Jetson device, could you please give me some information about how to do it? Like, are you using docker on your Jetson device? Did you optimized the network with TensorRT?

Thank you!
