### ISSUE TITLE
Cuda Out of memory

### ISSUE THREAD

**Issue by sivaariram** [NVIDIA/semantic-segmentation#45]
It was working fine with all the models, and then I modified the demo.py for offline video frames segmentation, this was working fine as well and when I started testing again and again now it is showing cuda out of memory error. Any Idea for reducing the batch size or something else ?

flash@flash:~/Documents/semantic-segmentation$ CUDA_VISIBLE_DEVICES=0 python3 demo1.py --demo-image images/F0000.png --snapshot ./pretrained_models/kitti_best.pth --save-dir Results/ 
Using regular batch norm
Traceback (most recent call last):
  File "demo1.py", line 30, in <module>
    net = network.get_net(args, criterion=None)
  File "/home/flash/Documents/semantic-segmentation/network/__init__.py", line 16, in get_net
    criterion=criterion)
  File "/home/flash/Documents/semantic-segmentation/network/__init__.py", line 44, in get_model
    net = net_func(num_classes=num_classes, criterion=criterion)
  File "/home/flash/Documents/semantic-segmentation/network/deepv3.py", line 225, in __init__
    wide_resnet = torch.nn.DataParallel(wide_resnet)
  File "/home/flash/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 136, in __init__
    self.module.cuda(device_ids[0])
  File "/home/flash/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/flash/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/flash/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/flash/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/flash/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

**Comment by bryanyzhu** [comment]
Maybe there are residual memory left from your previous run. Make sure `nvidia-smi` shows zero memory consumption before each run. 

FYI, it is not efficient to run `demo.py` for each frame in a video, because everytime the model needs to be built and loaded. This is slow and may cause such OOM error. A better way is to modify `demo.py`, read the video inside the script, load the model once, and inference for all the frames. I can provide an example later.

**Comment by sivaariram** [comment]
@bryanyzhu yes, it is because of residual memory, I just restarted my system it is fine now. I am reading the video inside the demo.py, but I have some issue in writing the video file from colorized image(Image is not a numpy array) so I converted the image to numpy array because I am using CV2 write, but even after the conversion, it is storing gray image, not the colorized.

**Comment by kwea123** [comment]
@sivaariram you just need to do `.convert('RGB')` after the `Image`.
Or I have an example: https://github.com/kwea123/semantic-segmentation/blob/master/inference.ipynb

**Comment by bryanyzhu** [comment]
@kwea123 Thank you for the help. 

@sivaariram I add a `demo_folder.py` in the pull request. You can use it to directly inference on a folder of images. You will also obtain colored predictions and overlapping predictions.

```
python demo_folder.py --demo-folder YOUR_FOLDER --snapshot ./pretrained_models/cityscapes_best.pth --save-dir YOUR_SAVE_DIR
```

**Comment by bryanyzhu** [comment]
@sivaariram If you have no further questions, please let us know, so we can close the issue.

**Comment by sivaariram** [comment]
@bryanyzhu I wrote a code for directly segmenting a video and writing back the output to the video file, but it takes lot of time for processing(approx 50 minutes for 10 minutes video file). Still, I have to test it with a real-time scenario. Is there is any possibility of improving processing time in the future ? or is there any other way to do it on my own?

**Comment by bryanyzhu** [comment]
@sivaariram Yes, you can improve the processing time on your own easily. 

1. Use a smaller network. We provide a SE-ResNeXt50 model in the readme, the download link is [here](https://drive.google.com/file/d/1aGdA1WAKKkU2y-87wSOE1prwrIzs_L-h/view). It should be at least twice faster without losing much accuracy. Actually, if you only visualize the mask, you won't notice the difference.

2. Do inference on a batch of images, not on a single image. For example, you can first read 8 video frames, turn it into a batch, 8x3x1024x2048, do the inference, and then separate the predictions. Set a batch size that can utilize all your GPU memory, that will be the best configuration. 

3. You can also rescale your input image to a smaller size. 1024x2048 is too large, you can inference on 256x512 input images, get the predictions, and interpolate back to 1024x2048. This will save ton of time.

Combing all three methods above, I think you should be able to achieve real-time or near-real-time inference. And it requires very minimal code change. 

If you have extra time, you can try some network pruning, compression or quantization technology. But that's beyond the scope of this repo.

**Comment by sivaariram** [comment]
@bryanyzhu Thank you so much I will try this and I think now we can close this issue.
