### ISSUE TITLE
Bug in evaluation transform

### ISSUE THREAD

**Issue by kwea123** [NVIDIA/semantic-segmentation#46]
For evaluation of mapillary, you use centercroppad
https://github.com/NVIDIA/semantic-segmentation/blob/47e14f1b1e7654e351a9b0afd2f9a7baa3e6bf51/datasets/__init__.py#L158
but you forgot to add `ignore_index=65` in the argument. By default the `ignore index` is `0` in the function definition, so this means you pad the GT mask into class 0, which is bird class..
This shouldn't have much impact on the numbers since it's originally very low, but this bug could be quickly fixed.

**Comment by karansapra** [comment]
I do believe you are right. I ll double check and fix it soon. Thanks @kwea123

**Comment by bryanyzhu** [comment]
Thank you for reporting the bug, I fixed in PR #51 .
