### ISSUE TITLE
Lane boundary detection

### ISSUE THREAD

**Issue by saishankarn** [NVIDIA/semantic-segmentation#48]
Does the model also detect lane boundaries ?

**Comment by bryanyzhu** [comment]
Our model only detects the boundary between road and sidewalk, not between lanes. 

If you want to detect lane boundaries, you can use our code to train a model on any lane segmentation dataset (e.g., [here](http://openaccess.thecvf.com/content_ECCV_2018/papers/Brook_Roberts_A_Dataset_for_ECCV_2018_paper.pdf)), I believe the result should be good.

**Comment by saishankarn** [comment]
thank you
