### ISSUE TITLE
problem occur when using "docker build -t nvidia-segmgentation -f Dockerfile ."

### ISSUE THREAD

**Issue by sde123** [NVIDIA/semantic-segmentation#49]
Dear code engineer:
thank you very much for your work in semantic segmentation. But when i use the command "docker build -t nvidia-segmgentation -f Dockerfile", 
I got the following error：

bc5bb9379810:_ Download complete 
8d2533535f88: Download complete 
15c2061baa94: Download complete 
fe35706ec086: Download complete 
ef06e50267e2: Download complete 
24569ba3e1d3: Download complete 
c49dc7cbf15c: Downloading 
34e55507c797: Waiting 
c26e49a3c2c6: Waiting 
7f6410878ec9: Waiting 
97f3bcccbcdf: Waiting 
3f9a50c314fa: Waiting 
d6c800c70bb2: Waiting 
9c785de98406: Waiting 
acb71385d77d: Waiting 
ea9fb98cc638: Waiting 
08e43405860a: Waiting 
02899df1d7b5: Waiting 
66e5d0f2b0fa: Waiting 
46bb7884fc3b: Waiting 
af50c16f8064: Waiting 
a8c14d818405: Waiting 
8c3f313defdf: Waiting 
unauthorized: authentication required
root@dai-System-Product-Name:/home/dai/code/semantic_segmentation/1/semantic-segmentation#

Could you please tell me how to solve this problem? thank you.

**Comment by bryanyzhu** [comment]
@karansapra Can you help with this? Thank you.

**Comment by sde123** [comment]
@bryanyzhu 
Thank you for your reply. I have solved the above problem, but i see the line 22 of cityscapes.py which needs the "aug_root = cfg.DATASET.CITYSCAPES_AUG_DIR", Could you tell me where to find the CITYSCAPES_AUG_DIR, I cannot find it in my cityscapes dataset which contains leftImg8bit_trainvaltest and gtFine_trainvaltest.
Thank you very much!

**Comment by bryanyzhu** [comment]
Sorry for the confusion, `CITYSCAPES_AUG_DIR ` is where to store the augmented image-label pairs by using our video prediction models. It is not in the original Cityscapes dataset.

**Comment by sde123** [comment]
@bryanyzhu 
Thank you for your reply.
I have a problem that when you submit your result to the cityscapes website, do you submit the labelIDs?, I see the cityscapes website requires the labelIDs, but I cann not find the labellDs in your code. Could you please tell me where to find it?

**Comment by bryanyzhu** [comment]
Yes, we submit the labelIDs. The transformation and definition of labelID, trainID, etc can be found in [cityscapes_labels.py](https://github.com/NVIDIA/semantic-segmentation/blob/master/datasets/cityscapes_labels.py).

You can also try our `eval.py` or `demo.py`, the images of labelID are saved. Those are the black-white images. You can directly submit them to Cityscapes. Let me know if you have further questions.

**Comment by sde123** [comment]
> 
> 
> @karansapra Can you help with this? Thank you.



> 
> 
> Sorry for the confusion, `CITYSCAPES_AUG_DIR ` is where to store the augmented image-label pairs by using our video prediction models. It is not in the original Cityscapes dataset.

**Comment by 1Konny** [comment]
@sde123 Hi. Could you please share us how did you solve this issue?

**Comment by DKandrew** [comment]
@1Konny I solved the problem by typing `docker login`
