### ISSUE TITLE
RGB values for different categories

### ISSUE THREAD

**Issue by chrismgeorge** [NVIDIA/semantic-segmentation#53]
Are the rgb values for each category somewhere in this directory?

**Comment by bryanyzhu** [comment]
Hi, do you mean the RGB value for color scheme of each class? Maybe here

https://github.com/NVIDIA/semantic-segmentation/blob/master/datasets/cityscapes.py#L24

If I misunderstand your question, please let me know more details. Thank you.

**Comment by chrismgeorge** [comment]
Yeah, so I guess you used that instead of assigning rgb values to each class. 

So there doesn't exist like a dictionary somewhere that is like:
{person: [252, 0, 10], car: [20, 10, 20], ... etc.}

**Comment by bryanyzhu** [comment]
We didn't write it like a dictionary, but here is the dictionary showing the mapping if you like:

```
road: 128, 64, 128
sidewalk: 244, 35, 232
building: 70, 70, 70
wall: 102, 102, 156
fence: 190, 153, 153
pole: 153, 153, 153
traffic light: 250, 170, 30
traffic sign: 220, 220, 0
vegetation: 107, 142, 35
terrain: 152, 251, 152
sky: 70, 130, 180
person: 220, 20, 60
rider: 255, 0, 0
car: 0, 0, 142
truck: 0, 0, 70
bus: 0, 60, 100
train: 0, 80, 100
motorcycle: 0, 0, 230
bicycle: 119, 11, 32
```

**Comment by chrismgeorge** [comment]
That's awesome!
Exactly what I was looking for, thank you!
