### ISSUE TITLE
Error during evaluation:   mod = importlib.import_module(module)

### ISSUE THREAD

**Issue by SaqibMamoon** [NVIDIA/semantic-segmentation#54]
Hi, I would like to thanks and appreciate for sharing the code of such a impressive work.
During the evaluation command using eval.py it gives me the following error:

python eval.py --dataset kitti  --snapshot ./logs/ckpt/default/kitt network.deepv3.DeepV3Plus_crop_size_368_cv_2_dataset_kitti_lr_0.025_PT --arch DeepSRNX50V3PlusDm_1 --ckpt_path ./logs/ckpt/default/kitt-network.deepv3.DeepV3Plus_crop_size_368_cv_2_dataset_kitti_lr_0.025_PT/ --mode test --split test --dataset_cls kitti

```
Traceback (most recent call last):
  File "eval.py", line 605, in <module>
    main()
  File "eval.py", line 565, in main
    net = get_net()
  File "eval.py", line 383, in get_net
    net = network.get_net(args, criterion=None)
  File "/semantic-segmentation-master/network/__init__.py", line 16, in get_net
    criterion=criterion)
  File "/semantic-segmentation-master/network/__init__.py", line 44, in get_model
    mod = importlib.import_module(module)
  File "/data/user/anaconda3/envs/vtorch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'DeepSRNX50V3PlusDm_'

```
could you please share the right command for evaluation on test dataset.

**Comment by bryanyzhu** [comment]
Hi, I think it is a typo. The network we have is `DeepSRNX50V3PlusD_m1 `, not `DeepSRNX50V3PlusDm_1 `.

**Comment by SaqibMamoon** [comment]
Dear bryanyzhu, Thanks for the correction. Now i'm able to run the eval.py.
Please correct me if i'm wrong! 
After going through data-loader, and eval.py files,  I think we can only perform evaluation on validation datasets not test dataset, right ?
Like we can run the model on val set of cityscapes but can't use it on test set of cityscapes or kitti dataset.

**Comment by bryanyzhu** [comment]
We can run inference on test set of both datasets.

Please see file below for testing on Cityscape
https://github.com/NVIDIA/semantic-segmentation/blob/master/scripts/submit_cityscapes_WideResNet38.sh

and this file for testing on KITTI,
https://github.com/NVIDIA/semantic-segmentation/blob/master/scripts/test_kitti_WideResNet38.sh

**Comment by SaqibMamoon** [comment]
> We can run inference on test set of both datasets.
> 
> Please see file below for testing on Cityscape
> https://github.com/NVIDIA/semantic-segmentation/blob/master/scripts/submit_cityscapes_WideResNet38.sh
> 
> and this file for testing on KITTI,
> https://github.com/NVIDIA/semantic-segmentation/blob/master/scripts/test_kitti_WideResNet38.sh

Thanks a lot! It's clear now!!
