### ISSUE TITLE
A problem occurred while I was running _aug.sh

### ISSUE THREAD

**Issue by antahikari** [NVIDIA/semantic-segmentation#56]
amax@amax:/data/semantic-segmentation/sdcnet$ sudo bash _aug.sh
[sudo] amax 的密码： 
Loaded checkpoint '../pretrained_models/sdc_cityscapes_vrec.pth.tar' (at epoch 390)
Augmenting aachen for mode rgb_image
/pytorch/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
/opt/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/pytorch/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

The 622 question is endless. Do you know how to solve it？Thank you very much.

**Comment by bryanyzhu** [comment]
This warning is because new version of PyTorch (maybe pytorch 1.2 and later) requires new way of writing forward function. I don't know exactly how to solve this problem, but try to add `@staticmethod` before `forward` function. Here is an example you can refer to, https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html

You can also check online, here are related posts,
https://discuss.pytorch.org/t/legacy-autograd-function-with-non-static-forward-method-is-deprecated-and-will-be-removed-in-1-3/69869

Hope it helps.

**Comment by antahikari** [comment]
Thank you for your reply. When I run the _aug.sh, I find that the enhancement process is in progress while warning.

In addition, can your model be used for video semantic segmentation? I have seen your demo, which works very well, but I don't see any content related to video data in your description.

**Comment by bryanyzhu** [comment]
Yes, it is just warning, so the process won't be interrupted.

Yes, you can use it for video semantic segmentation. Just use the `demo_folder.py` https://github.com/NVIDIA/semantic-segmentation/blob/master/demo_folder.py. 

This script can handle a folder of images, as long as you store the images in order, such as `0001.jpg`, `0002.jpg`, ..., `0100.jpg`, etc. So if you have a video, you can first decode the video into frames first and use the script to inference. 

Or you can directly modify the `demo_folder.py` to accept video input.

**Comment by karansapra** [comment]
@antahikari Closing this issue. Please feel free to reopen if you see the issue.
