### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by ayinaaaaaa** [NVIDIA/semantic-segmentation#57]
hi,Sorry to bother you,  when I run demo.py,there is a problem about "AttributeError: 'tuple' object has no attribute 'cpu'".could you give me some advice?Thank you!!!!

**Comment by bryanyzhu** [comment]
Is the problem fixed? If not, can you describe the details, like what is the input, which model you use, what command line you use and what is the error message. Thank you.

**Comment by ayinaaaaaa** [comment]
The problem has been solved. Thank you for your reply！Thank you !!

**Comment by TMRajeh** [comment]
how the problem solved, could you share the solution?

**Comment by samra-irshad** [comment]
Same issue, how it is solved?
