### ISSUE TITLE
Reproducing the mIoU of 81.4

### ISSUE THREAD

**Issue by MahdiehP** [NVIDIA/semantic-segmentation#58]
Hi, would you please define the config for mIoU of 81.4?

What is the cv_split, inference mode, the scales and the pre-trained model?

Thanks

**Comment by bryanyzhu** [comment]
You mean the number in the paper table 3? It is cv split 0, sliding inference, single scale. That model is for ablation study in the paper, so we don't provide its weight here in this repo. If you want to reproduce the score, you can use `cityscapes_cv0_wideresnet38_nosdcaug.pth ` as an approximation. This model has a single scale mIoU of 81.5.

**Comment by karansapra** [comment]
@bryanyzhu  @MahdiehP can we close this issue ?

**Comment by bryanyzhu** [comment]
I'm fine closing it.
