### ISSUE TITLE
Error when attempting training: 'No Support for SyncBN without Apex'

### ISSUE THREAD

**Issue by rod409** [NVIDIA/semantic-segmentation#59]
Hello, I am trying to use the train_kitti script within docker but am getting the output below regarding 'No Support for SyncBN without Apex'. I am not sure what I need to do, can you help? In case it is related, the original docker file failed to build during apex setup so I changed the "Install Apex" line to checkout an earlier commit of Apex before running the setup. Thanks!

> Total world size:  1
> Traceback (most recent call last):
>   File "train.py", line 318, in <module>
>     main()
>   File "train.py", line 156, in main
>     assert_and_infer_cfg(args)
>   File "/home/test/semantic-segmentation/config.py", line 101, in assert_and_infer_cfg
>     raise Exception('No Support for SyncBN without Apex')
> Exception: No Support for SyncBN without Apex
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
>     main()
>   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
>     cmd=process.args)
> subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=0', '--dataset', 'kitti', '--cv', '2', '--arch', 'network.deepv3.DeepWV3Plus', '--snapshot', './pretrained_models/cityscapes_best.pth', '--class_uniform_pct', '0.5', '--class_uniform_tile', '300', '--lr', '0.001', '--lr_schedule', 'poly', '--poly_exp', '1.0', '--syncbn', '--sgd', '--crop_size', '360', '--scale_min', '1.0', '--scale_max', '2.0', '--color_aug', '0.25', '--max_epoch', '90', '--img_wt_loss', '--wt_bound', '1.0', '--bs_mult', '2', '--apex', '--exp', 'kitti_ft', '--ckpt', './logs/', '--tb_path', './logs/']' returned non-zero exit status 1.

**Comment by bryanyzhu** [comment]
Hi, usually I use conda to build the environment, I don't use the container for a long time.

Please follow the steps below if you are comfortable using conda. 
```
# Build a conda enviroment for PyTorch 1.0.1
conda create -n semseg_pth101_cu100 python=3.7
conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=10.0 -c pytorch
pip install opencv-python scipy tqdm scikit-image tensorboardX
pip uninstall pillow
pip install pillow==6.0.0

# Install Apex for SyncBN and AMP
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by rod409** [comment]
> Hi, usually I use conda to build the environment, I don't use the container for a long time.
> 
> Please follow the steps below if you are comfortable using conda.
> 
> ```
> # Build a conda enviroment for PyTorch 1.0.1
> conda create -n semseg_pth101_cu100 python=3.7
> conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=10.0 -c pytorch
> pip install opencv-python scipy tqdm scikit-image tensorboardX
> pip uninstall pillow
> pip install pillow==6.0.0
> 
> # Install Apex for SyncBN and AMP
> git clone https://github.com/NVIDIA/apex
> cd apex
> pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```

When I ran these commands and tried to run the kitti script I get an import "cannot import 'amp' from 'apex'.  I looked at all the previous output and apex shows build errors. I'm not sure why it fails.

**Comment by bryanyzhu** [comment]
Then it is the error of building apex, I suggest to ask this in the apex's repo https://github.com/NVIDIA/apex, and attach build error messages.

**Comment by rod409** [comment]
I was able to build apex by using a more recent version of PyTorch. I am running into the same problem as before though. 'No Support for SyncBN without Apex'

**Comment by bryanyzhu** [comment]
Hi, this error is coming from this line

https://github.com/NVIDIA/semantic-segmentation/blob/master/config.py#L96-L101

As you can see, there are two things that can cause this exception. One is ``import apex``, the other is ``__C.MODEL.BNFUNC = apex.parallel.SyncBatchNorm``. Maybe there are more reasons, but please first try these two commands in your python environment to see which one causes the error,

```
$ python
$ import apex
$ func = apex.parallel.SyncBatchNorm
```

**Comment by rod409** [comment]
> Hi, this error is coming from this line
> 
> https://github.com/NVIDIA/semantic-segmentation/blob/master/config.py#L96-L101
> 
> As you can see, there are two things that can cause this exception. One is `import apex`, the other is `__C.MODEL.BNFUNC = apex.parallel.SyncBatchNorm`. Maybe there are more reasons, but please first try these two commands in your python environment to see which one causes the error,
> 
> ```
> $ python
> $ import apex
> $ func = apex.parallel.SyncBatchNorm
> ```

Neither line returns an error.

**Comment by ajtao** [comment]
Hi @rod409 , would you please put `print(args)` on config.py line 94, and share the output. So we can see what your cmdline args are? It's really odd that this error is getting thrown with the args in the training script, which should include both **--syncbn** and **--apex**.

**Comment by ajtao** [comment]
Oh, i see args.apex is getting overwritten in train.py https://github.com/NVIDIA/semantic-segmentation/blob/master/train.py#L137-L138. So you probably have WORLD_SIZE=1 (meaning 1 GPU). You have a few options, i believe:

1. i think you should be able to simply comment out line 138. Apex should still work with 1 GPU.
2. if that doesn't work, could just remove --syncbn and --apex from the training script. That should work. That'd just be using normal batchnorm, not the sync type, which should be fine on one GPU
3. If you have more than 1 GPU, then set world size to the number GPUs and just rerun the training script as-is.

**Comment by karansapra** [comment]
I did a quick test to verify, if you 1 GPU, you should able to remove `--syncbn` flag from `scripts/train_kitti_WideResNet38.sh` and it should work on 1 GPU.

**Comment by jowens** [comment]
You guys are awesome. Many thanks.

**Comment by rod409** [comment]
removing the --syncbn flag with one GPU worked, I got passed the error.  I am still not able to train but this is from pytorch not your code. This has to do with torch.cuda.device_count() returning 0 and causing a batch_size of 0.

Thanks for helping everyone.
