### ISSUE TITLE
[sdcnet] List of string in a batch during training

### ISSUE THREAD

**Issue by zetyquickly** [NVIDIA/semantic-segmentation#60]
Hello,

I've tried to applt SDCNet subproject on a custom dataset. I pass as `--train-file` path to the root of a dataset consist of several dirs with images enumerated according the time.

And I cannot figure out the expected behaviour of a training step because of the following:
1. Dataset class returns string in a dict https://github.com/NVIDIA/semantic-segmentation/blob/master/sdcnet/datasets/frame_loader.py#L99
2. And then the function which tries to move list of strings to cuda (I mean `batch['input_files']`) https://github.com/NVIDIA/semantic-segmentation/blob/master/sdcnet/main.py#L345 

What I do wrong? :)

**Comment by lsjAI** [comment]
According to the line 397 in main.py (function 'evaluate'):
Change "inputs = {k: [b.cuda() for b in batch_cpu[k]] for k in batch_cpu}" to 
"inputs = {k: [b.cuda() for b in batch_cpu[k]] for k in batch_cpu if k == 'image'}"

**Comment by zetyquickly** [comment]
> According to the line 397 in main.py (function 'evaluate'):
> Change "inputs = {k: [b.cuda() for b in batch_cpu[k]] for k in batch_cpu}" to
> "inputs = {k: [b.cuda() for b in batch_cpu[k]] for k in batch_cpu if k == 'image'}"

Thanks! 
I think it might solve a problem
