### ISSUE TITLE
some problem  about custom_coarse_prob

### ISSUE THREAD

**Issue by laojiangwei** [NVIDIA/semantic-segmentation#62]
hello, i find your custom_coarse_prob in train_cityscapes_sota.yml is 0.5, but in your paper you write “Teacher predictions that exceed the threshold become true labels, otherwise the pixel is labelled as ignore class. In practice we use a threshold of 0.9.”, I'm very confused about whether this represents the same value.

**Comment by karansapra** [comment]
Yes, that should be the same value, after the arxiv submission, we did a little more hyper-param recently with multiple runs and found that 0.05 IOU improvements on average when we use a threshold of 0.5.  Our 85.1 IOU obtained on cityscapes (mentioned in our arxiv paper) was achieved with 0.9 threshold value.

Please note that our codebase is reflective of our 85.4 IOU on cityscapes with 2 new changes: Supervised loss attach to heirarchial branches as well as the update hyper-param values that are reflected in the code base but not the paper. 

We plan to update the paper in the upcoming future. Hope the is clarifies.

**Comment by laojiangwei** [comment]
thanks~
