### ISSUE TITLE
[docker] sw-nvdl-docker/pytorch:19.10-py3 is not available

### ISSUE THREAD

**Issue by xlamb1412** [NVIDIA/semantic-segmentation#63]
Could you please public the docker image?

**Comment by karansapra** [comment]
It seems our reference is wrong,  I ll fix the reference today, it should be pulling from the public version from link below.

https://ngc.nvidia.com/catalog/containers/nvidia:pytorch/tags

**Comment by sudharsanBabu** [comment]
Can we use the official Pytorch docker image rather than NGC?
