### ISSUE TITLE
Missing definition for `wider_resnet38_a2` in wider_resnet.py file

### ISSUE THREAD

**Issue by IvanFei** [NVIDIA/semantic-segmentation#67]
Hello,   @ajtao 

You used the backbone named 'wider_resnet38_a2' In the class `wrn38` [line 405, wider_resnet.py]. 
However,  I could't find the backbone module in this project. 

Looking forward your reply

ref: [https://github.com/NVIDIA/semantic-segmentation/blame/main/network/wider_resnet.py](url)

**Comment by ajtao** [comment]
https://github.com/NVIDIA/semantic-segmentation/blob/main/network/wider_resnet.py#L394

**Comment by IvanFei** [comment]
Thank you for your kind reply.

**Comment by IvanFei** [comment]
Hello, @ajtao 

Sorry to Interrupt. 

It seems that missing the "=" in Line 456 of "joint_transforms.py" .
origin codes: 
`scale_amt * pre_scale`

ref: https://github.com/NVIDIA/semantic-segmentation/blob/main/transforms/joint_transforms.py#L456

**Comment by ajtao** [comment]
Thanks, fixed.
