### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by daixiaolei623** [NVIDIA/semantic-segmentation#69]
Dear author
I only have two GPUs (GTX 1080) about 20 G, however, your code requires 32G of GPUs. 
Do you have any solution to reduce the GPU memory requirements?
Thank you very much.

**Comment by ajtao** [comment]
You can shrink the crop size, that's a good way. I would suggest taking the crop size from 1024,2048 down to something like 800x800, something like that. The accuracy of the model will fall a little.
