### ISSUE TITLE
RGB discrepancy on Mapillary trained models

### ISSUE THREAD

**Issue by amil-rp-work** [NVIDIA/semantic-segmentation#75]
Hey!!!
I have tried using the pre-trained model of Mapillary dataset.  I already have access to the same dataset and have used the `config.json` that I obtained from it. They have a color code for each class. However when using `mapillary_ocrnet.HRNet_Mscale_fast-rattlesnake.pth` and `hrnetv2_w48_imagenet_pretrained.pth` I have observed that classes (for eg - billboard) has a range of RGB values  from 200 - 220.  I am using the `dump_folder.yml` with the following changes
```
# Run Evaluation and Dump Images on Cityscapes with a pretrained model

CMD: "python3 -m torch.distributed.launch --nproc_per_node=1 /content/semantic-segmentation/train.py"

HPARAMS: [
  {
   dataset: mapillary,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   bs_val: 1,
   eval: folder,
   eval_folder: '/content/tester',
   dump_assets: true,
   dump_all_images: true,
   n_scales: "0.25,0.5,1.0,2.0",
   do_flip: true,
   snapshot: "ASSETS_PATH/seg_weights/mapillary_ocrnet.HRNet_Mscale_fast-rattlesnake.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: '/content/tester_results/',
  },
]
```

I have 2 questions

1. Why are the colors not fixed for each class instead of a range(as mentioned above)?
2. Is there a discrepancy due to not pre-processing the image, if so how do I go about doing it?
3. How do I go about creating a grayscale mask for a single class from this?

**Comment by ajtao** [comment]
Hi Amil, could you please share an example image file (and the respective file name) as an example? The prediction of the network, while often good, is certainly not perfect, so perhaps what you're seeing is that the network thinks the billboard is two different things.

**Comment by amil-rp-work** [comment]
@ajtao Apologies, it seems to work well now! I was leveraging a different config file. Sorry for the inconvenience caused!
Can you suggest what is the best model checkpoint and set of methods to get the best performance?

**Comment by ajtao** [comment]
Yes, please refer to train_cityscapes_sota.yml for the best recipe.

**Comment by amil-rp-work** [comment]
These are the parameters of cityscapes, how to get the best `.yml` file for inferencing on **Mapillary dataset**. Also which checkpoint is the best for mapillary?

**Comment by ajtao** [comment]
Using eval_mapillary.yml should deliver 61.05 IOU, that's our best model. That recipe uses the fast-rattlesnake snapshot from our google drive.

**Comment by amil-rp-work** [comment]
@ajtao Got it, thanks!!!
