### ISSUE TITLE
Did the trunk model and attention branch train together?

### ISSUE THREAD

**Issue by czczup** [NVIDIA/semantic-segmentation#79]
I've noticed that trunk and attention branch seem to be trained together in this code. If I already have a pretrained truck model, can I freeze it and just train an attention branch? I've tried to do this, but it doesn't seem to work. I got a similar result to AvgPool, with no significant improvement. Maybe I should train all the parameters together? Can you give me some advice?

**Comment by ajtao** [comment]
Definitely, train it together.

**Comment by czczup** [comment]
> Definitely, train it together.

Thanks
