### ISSUE TITLE
Training time 

### ISSUE THREAD

**Issue by bberry25** [NVIDIA/semantic-segmentation#81]
I have a question about the training time and train/val/test set quantities of each dataset Mapillary and Cityscapes, using HRNet + OCR + multi-scale attention.

**Comment by ajtao** [comment]
Mapillary =~ 20k images, Cityscapes =~ 3k images. Training time for mapillary on 4 nodes is about 5 days. I think Cityscapes training time is about 1.5 days on 2 nodes.
