### ISSUE TITLE
a strang problem when I run the train code

### ISSUE THREAD

**Issue by purse1996** [NVIDIA/semantic-segmentation#86]
When I run python -m runx.runx scripts/train_cityscapes.yml -i
a strange problem occurs:
/bin/sh: 1: cd: can't cd to logs/train_cityscapes/ocrnet.HRNet_Mscale_micro-anaconda_2020.10.24_22.12/code
can't open file 'train.py': [Errno 2] No such file or directory
subprocess.CalledProcessError: Command '['/home/shuaibin/anaconda3/envs/pytorch_130/bin/python', '-u', 'train.py', '--local_rank=7', '--dataset', 'cityscapes', '--cv', '0', '--syncbn', '--apex', '--fp16', '--crop_size', '1024,2048', '--bs_trn', '1', '--poly_exp', '2', '--lr', '5e-3', '--rmi_loss', '--max_epoch', '175', '--n_scales', '0.5,1.0,2.0', '--supervised_mscale_loss_wt', '0.05', '--snapshot', 'ASSETS_PATH/seg_weights/ocrnet.HRNet_industrious-chicken.pth', '--arch', 'ocrnet.HRNet_Mscale', '--result_dir', 'logs/train_cityscapes/ocrnet.HRNet_Mscale_micro-anaconda_2020.10.24_22.12']' returned non-zero exit status 2.

Do you have any suggestions? Thank you very much.

**Comment by ajtao** [comment]
The code is trying to create a directory under the folder `logs`. You will need to create that directory once.

**Comment by purse1996** [comment]
Thank you, But there is the folder of logs/train_cityscapes/....,. But when I run the code, the problem still exists.

**Comment by purse1996** [comment]
It's because of the version of runx. I change the version of runx as the Dockfile. The code can run. Thank you very much.

**Comment by anyuzoey** [comment]
Hi @purse1996 
I got the same error with the newest runx

python -m runx.runx scripts/train_cityscapes.yml -i
Copying codebase to logs/train_cityscapes/ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59 ...
Running job train_cityscapes_ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59
cd logs/train_cityscapes/ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59/code; PYTHONPATH=logs/train_cityscapes/ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59/code exec python -m torch.distributed.launch --nproc_per_node=8 train.py --dataset cityscapes --cv 0 --syncbn --apex --fp16 --crop_size 1024,2048 --bs_trn 1 --poly_exp 2 --lr 5e-3 --rmi_loss --max_epoch 175 --n_scales 0.5,1.0,2.0 --supervised_mscale_loss_wt 0.05 --snapshot ASSETS_PATH/seg_weights/ocrnet.HRNet_industrious-chicken.pth --arch ocrnet.HRNet_Mscale --result_dir logs/train_cityscapes/ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59 
/bin/sh: 1: cd: can't cd to logs/train_cityscapes/ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59/code

pip install --upgrade runx
Requirement already up-to-date

**Comment by anyuzoey** [comment]
I was fixed by adding the full directory to LOGROOT in .runx file
LOGROOT: /home/username/semantic-segmentation/logs
