### ISSUE TITLE
Validation score v/s paper's score

### ISSUE THREAD

**Issue by sborse3** [NVIDIA/semantic-segmentation#88]
Thanks for the repository, great job!! The paper reports score of 85.4 on val with multi-scale attention and without coarse training. Is this the same model as the 84.7 which we train without coarse annotations? If not, how to reproduce the 85.4% score without coarse annotations

**Comment by karansapra** [comment]
Hi @sborse3 sorry what do you mean by the same model? Yes, it's same architecture without the mutli-scale attention head. Those are also multi-scale evaluation just for your reference. 

I am assuming you are referring to Table 2 here. They are all using same architecture. When we added our MS attention. We keep base architecture the same.

**Comment by karansapra** [comment]
Also what is the 84.7 number you are referring too ?  did you meant 84.9 ?

**Comment by sborse3** [comment]
Thanks @karansapra  I'll let you know how it goes :)
