### ISSUE TITLE
Evaluating on the test set

### ISSUE THREAD

**Issue by sborse3** [NVIDIA/semantic-segmentation#90]
Is there functionality to evaluate on test set, or dump all images outputs for test set?

**Comment by karansapra** [comment]
Yes.

https://github.com/NVIDIA/semantic-segmentation/blob/main/utils/misc.py#L247

https://github.com/NVIDIA/semantic-segmentation/blob/main/train.py#L224

Let us know if you see issues.

**Comment by sborse3** [comment]
Thanks for pointing it out! I was able to generate some results.
