### ISSUE TITLE
Could you please share your auto-labelling code?

### ISSUE THREAD

**Issue by happyCodingSusan** [NVIDIA/semantic-segmentation#91]
@bryancatanzaro, amazing work! Thanks for sharing!!
You mentioned in your paper, "By using our auto-labelling approach, we can improve the label quality, which in turn helps the model IOU". I wonder if you could please share the auto-labelling code.

**Comment by karansapra** [comment]
Hi @happyCodingSusan the auto-labelling code is part of the repo. 

https://github.com/NVIDIA/semantic-segmentation/blob/main/train.py#L226

**Comment by karansapra** [comment]
Closing issue, feel free to re-open it.
